### PR TITLE
change stable to be a symlink to the latest released version

### PR DESCRIPTION
**Pull request by mattip**
The idea is to make the `stable` directory a symlink to the latest released documents, to remove one point of friction when releasing a new version. This is the way numpy does it: the [stable symlink](https://github.com/numpy/doc) seamlessly works with github docs to point to the [1.19.0 docs](https://numpy.org/doc/stable/)

~This has a merge conflict since the docs are updated every night somehow the stable docs got out of sync?. I will rebase fix it if I can convince the maintainers as to the approach, but then it must be merged before the next nightly build~. Edit: Not clear why there is a conflict, the files on my checkout are identical.

The commits to reconstruct this were (on linux where symlinks work)
```
git checkout site
git pull
git checkout -b stable
cd docs
git rm -r 1.6.0
git commit -m"remove links in 1.6.0"
git mv stable 1.6.0
git commit -m"move stable to 1.6.0"
ln -s 1.6.0 stable
git add stable
git commit -m"recreate stable as a soft link to 1.6.0"
git push
```

### CODE REVIEW

**Comment by mattip** [comment]
The [preview](https://5f4d0d1cd533640007002e66--pytorch-dot-org-preview.netlify.app/docs/stable/index.html) works, stable documents are visible even though they are a symlink.

**Review by zou3519 — APPROVED** [review]
This is amazing -- the reason why I put in the redirect pages way back when was because I didn't think github pages would support symlinks. The symlinks are a much cleaner solution and will definitely improve our docs build process

**Comment by brianjo** [comment]
@mattip Thanks for this PR. I'm having a little trouble fixing the conflict. If you could do so, please feel free to fix and merge. (I can fix the file later if there's a data loss.)

**Comment by mattip** [comment]
CI is green. I cannot merge (no permissions).

**Comment by brianjo** [comment]
Awesome! Thanks @mattip!

**Pull request merged**
