### PR TITLE
Update to ROCm5.3 for nightly

### PR DESCRIPTION
**Pull request by jithunnair-amd**

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@atalman @malfet All ROCm CI jobs passed. Netlify preview looks good. Can we please merge this?

**Comment by malfet** [comment]
@jithunnair-amd I though Andrey revamped the system recently to use release matrix and do automated updates (as in https://github.com/pytorch/pytorch.github.io/pull/1214 ) so those manual one should no longer be neccesary

**Comment by atalman** [comment]
@jithunnair-amd No need to use manual update now anymore. Will check now why rocm 5.3 was not picked up in https://github.com/pytorch/pytorch.github.io/pull/1214
Also before merging we would need to make sure signal is green

**Comment by jithunnair-amd** [comment]
> @jithunnair-amd I though Andrey revamped the system recently to use release matrix and do automated updates (as in #1214 ) so those manual one should no longer be neccesary

That's just what I wanted to hear :)

@atalman Okay, feel free to close this PR if you'll be making the ROCm version upgrade in #1214

**Review by malfet — APPROVED** [review]
Hmm, than those changes seems correct to me, aren't they?

**Comment by atalman** [comment]
> Hmm, than those changes seems correct to me, aren't they?

Yes changes are correct, the way the generation was refactored is to still allow manual updates. However I think we should
1. Prefer automatic updates
2. Update on green signal

I will put up a PR to update acc_arch_ver_map automatically by taking latest versions of rocm and cuda available in release matrix.

**Comment by atalman** [comment]
closing this, not required anymore

**Pull request closed without merging**
