### PR TITLE
GitHub stars integration

### PR DESCRIPTION
**Pull request by patmellon**
This PR displays each hub card's GitHub star count and adds the ability to sort cards based on their counts. 

*Please note that due to the issue of the identity doc files sharing the same file name (for example `docs/master/_sources/generated/torch.nn.utils.prune.Identity.rst.txt` appears twice--with the word identity in both uppercase and lowercase) I am unable to do an interactive rebase to squash the commits. I also had to delete two of the identity files to pull in the latest upstream changes.)

### CODE REVIEW

**Comment by jlin27** [comment]
@patmellon - This change looks great!
 
1. Would it visually make more sense to move the sort filter under the search bar (mock-up below)? Currently it's floating between the filter tags and the search and feels a bit unintuitive.  
image

2. From the preview link, the sort dropdown isn't working for me :/ 

3. Could we add a star icon next to the octocat to cleary indicate that the number is a star count?

**Comment by patmellon** [comment]
@jlin27 - I pushed up some commits to address the sorting issue. During our weekly meeting tomorrow we'll ask @brucejlin about the style feedback you listed.

**Comment by brucejlin1** [comment]
@patmellon @jlin27 this change in placement of the Sort By looks great, thank you.

**Comment by jlin27** [comment]
Sweet! That change looks good to me. Thanks for modifying that!

**Comment by jlin27** [comment]
@patmellon - Are you able to pull in the `docs/master/generated/torch.nn.utils.prune.Identity.html` from my PR https://github.com/shiftlab/pytorch.github.io/pull/48?

I'm not able to merge this PR without that file present and I'm not able to modify your fork via the command line manual merge, I'm trying this alternative method. 

If this doesn't work, I can try to fork your fork and then make a pr from my fork to pytorch:site (since I'll be able to manually merge PRs from my fork)

**Comment by patmellon** [comment]
@jlin27 I added the file from your branch, but it looks like the merge conflict is still there. I'll look into adding all of the identity files back.

**Pull request closed without merging**
