### PR TITLE
Moving Site Deployment script to GHA

### PR DESCRIPTION
**Pull request by osalpekar**
We are moving all jobs to GHA across the PyTorch organization. This PR does this for the site deployment CCI job that exists in the pytorch.github.io repo. Note that this does not use caching in its current form - we can likely do this in a follow-up.

WIP: testing this without breaking anything

cc @atalman @svekars

### CODE REVIEW

**Comment by atalman** [comment]
We should also add deprecation of circleci workflow: https://github.com/pytorch/pytorch.github.io/blob/site/.circleci/config.yml

**Review by atalman — APPROVED** [review]
LGTM

**Comment by cjyabraham** [comment]
Hi @osalpekar, I've just deployed [a change to the PyTorch website](https://github.com/pytorch/pytorch.github.io/pull/1427) but it is not building as expected. Any ideas why?

**Comment by osalpekar** [comment]
Looks like the [push is still failing](https://github.com/pytorch/pytorch.github.io/actions/runs/5836648574) for GHA job on trunk, which is why the site is not getting built as expected. I'm going to bring back the CCI job temporarily until we can figure out the GHA issue. 

cc @atalman

**Comment by malfet** [comment]
@osalpekar when you did the migration, have you added the secrets to the workflow?

**Comment by osalpekar** [comment]
@malfet Yes, that's done here: https://github.com/pytorch/pytorch.github.io/blob/site/.github/workflows/build.yml#L16.

**Comment by malfet** [comment]
I remember seeing something like that in the past. Will push the fix once find out what was it

**Comment by malfet** [comment]
Ok, two things were missing: 
  - Pass secrets to composite workflow https://github.com/pytorch/pytorch.github.io/commit/8bae1646c565518426dcfc550ea6e9a24ea599c7 (as shown in this test https://github.com/pytorch/test-infra/blob/ed7237ab9f23fa1b2f29699cf75d85b4a2a590a5/.github/workflows/test_linux_job.yml#L25 )
  - Prefix name with `SECRET_` as shown in the abovementioned test https://github.com/pytorch/pytorch.github.io/commit/2a26558cbb958f80f834439cd53bf1d21c17745f

**Pull request merged**
