### PR TITLE
Update 1.3.0 and stable Persons of Interest and correct sidebar

### PR DESCRIPTION
**Pull request by jlin27**
Update Persons of Interest in v1.3.0 and stable to match that of v1.2.0
v1.2.0: https://pytorch.org/docs/1.2.0/community/persons_of_interest.html

Correct the incorrectly hyperlinked sidebars from the Persons of Interest page and the index.html

Below is a local build via `make serve` of the v1.3.0 Persons of Interest docs page: 

Screen Shot 2019-11-30 at 3 37 18 PM

### CODE REVIEW

**Comment by jspisak** [comment]
This looks correct. The changes i had made previously were just to add the 3 names (MSFT folks) to the ONNX section. any other changes @zou3519 you know that were made?

**Comment by zou3519** [comment]
I commented on https://github.com/pytorch/pytorch/pull/30579, but it looks like we deleted some lines and then added some other lines. I'm not sure what the final state should look like; if we're just re-adding back the 3 names to the onnx section we shouldn't have to delete the other lines

**Comment by jspisak** [comment]
@zou3519 - i see what you mean. If you want, i can open a clean PR and just add the 3 names to the ONNX section.

**Comment by jlin27** [comment]
@jspisak - I'd second approach (open a clean PR w/ just the 3 new names).

**Pull request closed without merging**
