### PR TITLE
Replace mobile with executorch on the getting started page

### PR DESCRIPTION
**Pull request by clee2000**
Not entirely sure what I'm doing, the preview works?

Redirects immediately to the executorch page

### CODE REVIEW

**Review by seemethere — APPROVED** [review]
Looks great! Looking towards @ali-khosh for a second look as well

**Review by svekars — APPROVED** [review]

**Comment by ali-khosh** [comment]
Please use "ExecuTorch" vs. "Executorch" when referring to the project for consistency. 

In this particular instance please replace Executorch with Edge and point it to https://pytorch.org/edge to make it consistent with the headers on other pages.

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Before we land this, is there a sign off(in form of a review for example) from someone that we are removing the mobile section?

**Comment by clee2000** [comment]
> Please use "ExecuTorch" vs. "Executorch" when referring to the project for consistency.

On most recent commit

> In this particular instance please replace Executorch with Edge and point it to https://pytorch.org/edge to make it consistent with the headers on other pages.
 https://docs.google.com/document/d/1slnDApwhccfKI2qf75eOtA4ilyMCGF1tM36GxMBOR4U/edit#heading=h.xys1j0me4mye says to replace mobile with executorch, do you want to replace mobile with edge instead?

**Comment by seemethere** [comment]
> Before we land this, is there a sign off(in form of a review for example) from someone that we are removing the mobile section? 

I'm guessing @ali-khosh would be the authority here

**Comment by ali-khosh** [comment]
@seemethere  yes please go ahead. OK to remove the PT Mobile link

**Comment by clee2000** [comment]
Closing this because it already happened in https://github.com/pytorch/pytorch.github.io/pull/1615

**Pull request closed without merging**
