### PR TITLE
[ROCm] Update the installation command to pip3

### PR DESCRIPTION
**Pull request by pruthvistony**
- ROCm supports only python3 packages

### CODE REVIEW

**Review by jithunnair-amd — APPROVED** [review]
LGTM

**Comment by pruthvistony** [comment]
@malfet @jeffdaily @sunway13
please review

**Review by malfet — CHANGES_REQUESTED** [review]
Python version support is not different between ROCM and other flavors. (i.e. only Python-3.x is supported)
So, please replace installation command to `pip3` for all flavors.

**Comment by pruthvistony** [comment]
> Python version support is not different between ROCM and other flavors. (i.e. only Python-3.x is supported)
> So, please replace installation command to `pip3` for all flavors.

@malfet,
I have added a commit as requested.

**Review by malfet — APPROVED** [review]

**Pull request merged**
