### PR TITLE
generate 1.10.1 docs and make them 'stable'

### LINKED ISSUE #898: 1.10.1 was released, but the documentation at https://pytorch.org/docs/stable says 1.10.0
There are a few choices of how to fix this:
- Rename the "1.10.1" documentation to "1.10" (with no micro-version), and fix the documentation generation scripts to respect this decision going forward
- Add the "1.10.1" documentation, make it the stable version, and add it to the version selector.
- ~Rename the "1.10.0" documentation to "1.10.1"~ (probably not the best choice)

@brianjo what should the path forward be? Personally I prefer the first one, if not for 1.10 then certainly for 1.11.

### PR DESCRIPTION
**Pull request by mattip**
@brianjo

Fixes #898

I installed pytorch 1.10.1, and in the docs directory of pytorch did `export RELEASE=1; make html`. I then copied the resulting documentation into a 1.10.1 directory here, added it to the version.html, and reset `stable` to point to 1.10.1.

### CODE REVIEW

**Comment by brianjo** [comment]
Thank you so much Matti! Looks good. I'll merge this after it passes tests.

**Comment by brianjo** [comment]
I think we might be missing the Google Analytics block in the generated pages. 

```
  <!-- Google Analytics -->
  
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-117752657-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-117752657-2');
    </script>
  
  <!-- End Google Analytics -->

```

**Comment by mattip** [comment]
> I think we might be missing the Google Analytics block in the generated pages.

fixed now.

**Comment by brianjo** [comment]
> > I think we might be missing the Google Analytics block in the generated pages.
> 
> fixed now.

Awesome. Thanks Matti!

**Pull request merged**
