### PR TITLE
Design changes

### PR DESCRIPTION
**Pull request by iinfin**
- colors
`fix color inconsistency`
`improve color contrast`
- html tags
`fix h1, h2... tag font sizes`
`fix header-paragraph style relation`
- images
`remake static logos`
`optimize images`
`add Github and Twitter logos`
- general
`clean up unused styles`
`fix formatting`
`fix main.css-bootstrap conflicts`

### CODE REVIEW

**Comment by iinfin** [comment]
@soumith I didn't know you were willing to make a complete redesign, happy to hear that. I'm a designer and I'd like to propose some concepts if it's okay.

In this PR, I didn't change the overall design, fixed many misused cases, like `h3` was used for title, font size edited to ~45 and then `h1 ` used for paragraph font size edited to 14 etc.
I also [remade logos](https://github.com/iinfin/pytorch.github.io/tree/master/static/img/logos), their sizes varied a lot and you used classes to resize/fit them into logo table.

Here's a screen shot, with slight color, font, and grid improvements on front.

pytorch

**Comment by iinfin** [comment]
@soumith Here's a quick sketch I made.

### about
about

### menu
menu

**Comment by soumith** [comment]
hey han. you should wait till next Sunday, the new website will go live.

**Comment by soumith** [comment]
it's a big revamp, and looks nothing like the existing site.

**Comment by iinfin** [comment]
@soumith alright then I'm closing the PR, I'll see if there's something for me to contribute after the redesign.

**Pull request closed without merging**
