### PR TITLE
Updating links 

### PR DESCRIPTION
**Pull request by surgan12**
Updating the links to http://pillow.readthedocs.io/en/ as the old ones are broken.

### CODE REVIEW

**Comment by vishwakftw** [comment]
This should not be changed here. Please modify the doc strings in torchvision instead.

**Comment by surgan12** [comment]
@vishwakftw ,the torchvision already has the same as mentioned in this commit .

**Comment by vishwakftw** [comment]
The docs are built periodically, so it might take some time for the changes to reflect. Please check the master docs too, and not the stable one.

**Comment by surgan12** [comment]
Okayy Thanks @vishwakftw .

**Comment by soumith** [comment]
for stable docs, this is the right fix. For master docs, we have to fix this in https://github.com/pytorch/vision

**Pull request merged**
