### PR TITLE
[LTS] Use --extra-index-url in LTS install matrix

### PR DESCRIPTION
**Pull request by jambayk**
This PR updates the LTS installation instructions to use ``--extra-index-url`. Partially addresses issue https://github.com/pytorch/pytorch/issues/76829.

### CODE REVIEW

**Review by seemethere — APPROVED** [review]

**Comment by pmeier** [comment]
Although the installation instructions now use the `--extra-index-url`, they still differ from the "regular" instructions. Compare

```
pip3 install torch==1.8.2+cu102 torchvision==0.9.2+cu102 torchaudio==0.8.2 --extra-index-url https://download.pytorch.org/whl/lts/1.8
```

with

```
pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cu102
```

- The computation backend, i.e. `cpu`, `cu102`, or the like, should be appended to the link rather than as local specifier to the package.
- With that done, the specific version pinning can also removed since the index only contains the correct wheels and thus `pip` automatically selects the latest.

**Comment by pmeier** [comment]
> I don't think we can remove the version pinning. When using `--extra-index-url`, pip still has access to the pypi repository so it will see the version on it as latest.

Good point! We could use the `--index-url` flag here instead. Not sure what is more disrupting

```
pip install torch --index-url https://download.pytorch.org/whl/lts/1.8/cpu
```

vs.

```
pip install torch==1.8.2 --extra-index-url https://download.pytorch.org/whl/lts/1.8/cpu
```

**Comment by seemethere** [comment]
> > I don't think we can remove the version pinning. When using `--extra-index-url`, pip still has access to the pypi repository so it will see the version on it as latest.
> 
> Good point! We could use the `--index-url` flag here instead. Not sure what is more disrupting
> 
> ```
> pip install torch --index-url https://download.pytorch.org/whl/lts/1.8/cpu
> ```
> 
> vs.
> 
> ```
> pip install torch==1.8.2 --extra-index-url https://download.pytorch.org/whl/lts/1.8/cpu
> ```

I'd say it's potentially very disrupting since using `--index-url` would make it so that we couldn't pull dependencies?

**Comment by pmeier** [comment]
My bad, sorry :facepalm:

**Review by malfet — APPROVED** [review]

**Review by malfet — CHANGES_REQUESTED** [review]
CheckRegen fails, have you updated `published_version.json` by hand?

**Review by malfet — APPROVED** [review]

**Pull request merged**
