### PR TITLE
Corrected liner typo in RReLU

### PR DESCRIPTION
**Pull request by championballer**
Corrected liner typo in docs/nn/RReLU

### CODE REVIEW

**Comment by championballer** [comment]
@jspisak Please review.

**Comment by jspisak** [comment]
what is the actual change you made? It is hard to tell from the diff.

**Comment by championballer** [comment]
In the description of RReLU on the nn.html page, changed liner to linear for rectified linear unit.

**Comment by jspisak** [comment]
oh i see now. I was a bit confused on why the diff had 41 lines added and subtracted for that one change. any idea?

(good catch btw.. :)  )

**Comment by championballer** [comment]
@jspisak Thanks, was just reading through the docs, and saw it. No idea about the 41 lines modification though. But the page is building well on preview.

**Comment by championballer** [comment]
@jlin27 Please review. :)

**Comment by jlin27** [comment]
Good catch @championballer!
Changes look good to me (I think the diff is picking up changes in end of line white spaces).

**Pull request merged**
