### PR TITLE
Add links to CUDA-11 nightly packages

### PR DESCRIPTION
**Pull request by malfet**

### CODE REVIEW

**Review by brianjo — APPROVED** [review]

**Comment by soumith** [comment]
do you want to merge this after the 1.7 release or do you want to merge now?

if you want to merge now, the stable entries are also filled for cuda11 and presumably the stable build doesn't have a cuda11 version

**Comment by jspisak** [comment]
Are we getting rid of the 'None' option here? Or else we need to add another button to the selector.

**Comment by malfet** [comment]
Thank you for the feedback, will add another column to selector

**Comment by soumith** [comment]
the  None option is still there, the css needs to be adjusted that's all.

**Comment by soumith** [comment]
currently, the divs are tagged as `col-md-3`, so they cant display this many options but you can play with that variable: https://www.w3schools.com/bootstrap/bootstrap_grid_examples.asp

for example `col-md-5` or something might work

**Comment by seemethere** [comment]
Something doesn't look right on the preview deploy, looks like we're getting CUDA 11.0 in the "Stable" category

**Comment by malfet** [comment]
I have following 3 variants:
Using `col-md`(5 columns of the same width): 
col-md
Using `col-md-2` for first 3 columns and `col-md-3` for remaining 2 (imo, creates unnecessary focus on None and CUDA-11 options but have a nice center line)
col-md-2-2-2-3-3
Using `col-md-3` for latest versions of major CUDA release and `col-md-2` for 10.1 and None:
col-md-3-2-3-2-2

**Comment by jspisak** [comment]
thanks for wireframing this up! I like the first one.. :)

**Comment by malfet** [comment]
@soumith I can do it now or later, as stable links should redirect to build from source instructions

**Comment by soumith** [comment]
> as stable links should redirect to build from source instructions

If you want to merge now, which I am fine with, then have the stable configs explicitly say "CUDA 11 is not yet supported with PyTorch 1.6. Either try the nightlies or wait for PyTorch 1.7"

**Review by seemethere — APPROVED** [review]

**Pull request merged**
